"""Causal replay and visual-debugger package for SmartStructureBot."""

SIMULATOR_VERSION = "SMARTSTRUCTUREBOT_SIMULATOR_PHASE_S1B_REALISTIC_PAPER_V1"
STRATEGY_VERSION = "SMARTSTRUCTUREBOT_SIMULATOR_BASELINE_V0_9"
ORDERS_ENABLED = False
PAPER_EXECUTION_ONLY = True
