'use strict';

const $=id=>document.getElementById(id);
const esc=value=>String(value??'—').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fmt=(value,digits=2)=>value==null||value===''?'—':Number(value).toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits});
const money=value=>value==null?'—':`${Number(value)<0?'-':''}R${Math.abs(Number(value)).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const pct=value=>value==null?'—':`${fmt(value,2)}%`;
const utc=value=>value==null?'—':new Date(Number(value)*1000).toISOString().replace('T',' ').replace('.000Z',' UTC');
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const state={sessions:[],library:[],data:null,paper:null,paperMap:new Map(),index:0,playing:false,timer:null,speed:1,cursorTime:null,mode:'trader',layers:{'HH/HL/LH/LL':true,'Meaningful swings':true,'Dominant protection':true,'Retracement':true,'Fibonacci':true,'M1 qualification':true,'Entry triggers':true,'Initial logical stop':true,'Emergency stop':true,'Targets':true,'Proven trails':true,'Bid / ask / spread':true,'Rejected recommendations':false,'Bug flags':true},views:{M1:{window:170,offset:0,priceZoom:1},M5:{window:100,offset:0,priceZoom:1}},drag:null,accountConfig:null,executionConfig:null};

function event(){return state.data.events[state.index];}
function paper(){if(!state.data)return null;const repriced=state.paperMap.get(state.index);if(repriced)return repriced;const snap=event().snapshot;return {canonical:snap.paper_execution||null,shadow_accounts:snap.shadow_accounts||[]};}
function canonicalPaper(){return paper()?.canonical||null;}
function paperFinal(){return state.paper?.final||state.data?.paper_final||null;}

async function jsonFetch(url,options){const response=await fetch(url,options);let payload;try{payload=await response.json();}catch{throw new Error(`Invalid response from ${url}`)}if(!response.ok)throw new Error(payload.error||`${response.status} ${response.statusText}`);return payload;}

async function boot(){
  bindControls();
  const health=await jsonFetch('/api/health');
  state.sessions=await jsonFetch('/api/sessions');
  $('healthStrip').innerHTML=`<span>Strategy <strong>${esc(health.strategy)}</strong></span><span>Causality <strong>${esc(health.status)}</strong></span><span>Execution <strong>PAPER ONLY</strong></span><span>Order calls <strong>${esc(health.order_api_calls)}</strong></span>`;
  populateSessions();
  applyPreset();
  await loadLibrary();
  if(state.sessions.length){const preferred=state.sessions.find(row=>row.session_id==='S1-CASE-02')||state.sessions[0];$('sessionSelect').value=preferred.session_id;await loadSession(preferred.session_id,false);}
  if(typeof $('accountDialog').showModal==='function')$('accountDialog').showModal();else $('accountDialog').setAttribute('open','');
}

function bindControls(){
  $('loadButton').onclick=()=>loadSession($('sessionSelect').value,true);
  $('accountButton').onclick=()=>{if(!$('accountDialog').open)$('accountDialog').showModal();};
  const submitAccount=async ev=>{ev.preventDefault();await applyAccountConfiguration();$('accountDialog').close();};
  $('accountForm').addEventListener('submit',submitAccount);
  $('applyAccount').onclick=submitAccount;
  $('capitalPreset').onchange=()=>{if($('capitalPreset').value!=='custom')$('customCapital').value=$('capitalPreset').value;};
  $('playButton').onclick=togglePlay;$('resetButton').onclick=()=>{pause();go(0);resetViews();};$('backButton').onclick=()=>{pause();step(-1);};$('forwardButton').onclick=()=>{pause();step(1);};
  $('significantButton').onclick=()=>jumpWhere(e=>e.event_priority>=55,1);$('entryButton').onclick=()=>jumpWhere(e=>e.director_decision.committed_action.startsWith('ENTER'),1);$('exitButton').onclick=()=>jumpWhere(e=>e.director_decision.committed_action.startsWith('EXIT'),1);$('reentryButton').onclick=()=>jumpWhere(e=>e.director_decision.committed_action.includes('REENTRY'),1);$('bugButton').onclick=()=>jumpWhere(e=>e.bug_flags.length>0,1);
  $('speedSelect').onchange=()=>{state.speed=Number($('speedSelect').value);if(state.playing){pause();togglePlay();}};$('jumpButton').onclick=()=>{pause();go(Number($('jumpInput').value));};
  $('modeSelect').onchange=()=>setMode($('modeSelect').value);$('presetSelect').onchange=applyPreset;$('timelineFilter').onchange=renderTimeline;$('diffButton').onclick=renderCustomDiff;$('downloadButton').onclick=downloadEvent;$('saveReview').onclick=saveReview;
  $('fitButton').onclick=resetViews;$('resetViewButton').onclick=resetViews;$('currentButton').onclick=()=>{state.views.M1.offset=0;state.views.M5.offset=0;renderCharts();};
  $('libraryButton').onclick=()=>{$('dataLibraryPanel').classList.remove('hidden');$('dataLibraryPanel').scrollIntoView({behavior:'smooth'});};$('closeLibrary').onclick=()=>$('dataLibraryPanel').classList.add('hidden');$('buildForm').addEventListener('submit',buildReplay);
  for(const id of ['m1Chart','m5Chart']){const canvas=$(id);canvas.addEventListener('mousemove',chartMouse);canvas.addEventListener('mouseleave',()=>{state.cursorTime=null;state.drag=null;renderCharts();});canvas.addEventListener('wheel',chartWheel,{passive:false});canvas.addEventListener('mousedown',chartDragStart);window.addEventListener('mouseup',()=>state.drag=null);}
  $('equityChart').addEventListener('click',equityJump);
  window.addEventListener('resize',renderAll);
  document.addEventListener('keydown',keyboard);
  renderLayerControls();
}

function populateSessions(){const select=$('sessionSelect');select.innerHTML=state.sessions.map(row=>`<option value="${esc(row.session_id)}">${esc(row.session_id)} · ${esc(row.symbol)} · ${esc(row.event_count??'?')} events${row.dynamic?' · dynamic':''}</option>`).join('');}

function currentConfigurations(){
  const preset=$('capitalPreset').value;const starting=Number(preset==='custom'?$('customCapital').value:preset);
  const account={account_currency:'ZAR',starting_balance:starting,risk_model:$('riskModel').value,risk_percent:Number($('riskPercent').value),fixed_risk_money:Number($('fixedRisk').value),maximum_account_risk_percent:Number($('maxRisk').value),maximum_emergency_risk_percent:Number($('maxEmergencyRisk').value),leverage:Number($('leverage').value),margin_warning_level:150,margin_call_level:100,stop_out_level:50,maximum_concurrent_positions:1,compounding:$('compounding').checked,unsafe_minimum_volume_override:$('unsafeOverride').checked};
  const execution={broker_profile:'XM_ESTIMATED_RESEARCH',cost_profile:$('costProfile').value,spread_model:$('spreadModel').value,fixed_spread_points:$('spreadModel').value==='FIXED_USER_SPREAD'?Number($('fixedSpread').value):null,slippage_model:$('slippageModel').value,fixed_slippage_points:0,commission_model:$('commissionModel').value,swap_model:$('swapModel').value,execution_timing_model:$('executionTiming').value,intrabar_policy:$('intrabarPolicy').value,session_seed:'SMARTSTRUCTUREBOT_S1B_SEED_20260803',partial_fraction:.5,triple_swap_weekday:2};
  if(!Number.isFinite(starting)||starting<=0)throw new Error('Starting capital must be a positive amount.');
  return {account,execution};
}

async function applyAccountConfiguration(){if(!state.data)return;const config=currentConfigurations();state.accountConfig=config.account;state.executionConfig=config.execution;$('narrativeBanner').innerHTML='<strong>Replaying money causally…</strong><span>The strategy ledger is unchanged while the paper account is recalculated.</span>';
  const result=await jsonFetch('/api/paper/reprice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:state.data.manifest.replay_session_id,account_configuration:config.account,execution_configuration:config.execution,include_shadows:true})});
  const originalStrategyHash=result.strategy_event_hash;state.paper=result;state.paperMap=new Map(result.paper_events.map(row=>[Number(row.event_number),row]));state.index=0;resetViews();renderAll();$('reviewStatus').textContent=`Paper account applied · strategy hash ${originalStrategyHash.slice(0,10)} unchanged by balance`;}

async function loadSession(sessionId,reprice){pause();$('narrativeBanner').innerHTML='<strong>Loading immutable session…</strong><span>Only closed candles and stored Director actions will appear.</span>';state.data=await jsonFetch(`/api/replay/session/${encodeURIComponent(sessionId)}`);state.paper=null;state.paperMap=new Map();state.index=0;state.cursorTime=null;resetViews(false);if(reprice&&state.accountConfig){await applyAccountConfiguration();}else renderAll();}

function setMode(mode){state.mode=mode;document.body.className=`mode-${mode}`;renderAll();}
function renderLayerControls(){$('layerControls').innerHTML=Object.keys(state.layers).map(name=>`<label><input type="checkbox" data-layer="${esc(name)}" ${state.layers[name]?'checked':''}>${esc(name)}</label>`).join('');document.querySelectorAll('[data-layer]').forEach(input=>input.onchange=()=>{state.layers[input.dataset.layer]=input.checked;renderCharts();});}
function applyPreset(){const preset=$('presetSelect').value;const all=Object.keys(state.layers);all.forEach(name=>state.layers[name]=false);if(preset==='CLEAN TRADING VIEW'){['Meaningful swings','Dominant protection','Entry triggers','Initial logical stop','Emergency stop','Targets','Proven trails','Bid / ask / spread'].forEach(name=>state.layers[name]=true);}else if(preset==='ENTRY REVIEW'){['HH/HL/LH/LL','Retracement','Fibonacci','M1 qualification','Entry triggers','Initial logical stop','Emergency stop','Bid / ask / spread'].forEach(name=>state.layers[name]=true);}else if(preset==='MANAGEMENT REVIEW'){['Meaningful swings','Dominant protection','Initial logical stop','Emergency stop','Targets','Proven trails','Bug flags'].forEach(name=>state.layers[name]=true);}else if(preset==='RE-ENTRY REVIEW'){['HH/HL/LH/LL','Retracement','M1 qualification','Entry triggers','Proven trails','Rejected recommendations'].forEach(name=>state.layers[name]=true);}else if(preset==='FULL DEBUG'){all.forEach(name=>state.layers[name]=true);$('modeSelect').value='debug';setMode('debug');}else{['Meaningful swings','Dominant protection','Entry triggers','Initial logical stop','Emergency stop','Targets','Proven trails'].forEach(name=>state.layers[name]=true);$('modeSelect').value='investor';setMode('investor');}renderLayerControls();renderAll();}

function resetViews(render=true){state.views={M1:{window:170,offset:0,priceZoom:1},M5:{window:100,offset:0,priceZoom:1}};if(render)renderCharts();}
function pause(){state.playing=false;clearTimeout(state.timer);$('playButton').textContent='Play';}
function togglePlay(){if(!state.data)return;if(state.playing){pause();return;}state.playing=true;$('playButton').textContent='Pause';const loop=()=>{if(!state.playing)return;if(state.index>=state.data.events.length-1){pause();return;}step(1);state.timer=setTimeout(loop,Math.max(35,800/state.speed));};loop();}
function step(delta){go(state.index+delta);}
function go(index){if(!state.data)return;state.index=clamp(Math.round(index),0,state.data.events.length-1);$('jumpInput').value=state.index;if(event().integrity.status==='FAIL')pause();renderAll();}
function jumpWhere(predicate,direction){if(!state.data)return;for(let index=state.index+direction;index>=0&&index<state.data.events.length;index+=direction){if(predicate(state.data.events[index])){pause();go(index);return;}}}
function keyboard(ev){if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(ev.code==='Space'){ev.preventDefault();togglePlay();}else if(ev.key==='ArrowRight'){ev.preventDefault();ev.shiftKey?jumpWhere(e=>e.event_priority>=55,1):step(1);}else if(ev.key==='ArrowLeft'){ev.preventDefault();step(-1);}else if(ev.key.toLowerCase()==='e')jumpWhere(e=>e.director_decision.committed_action.startsWith('ENTER'),1);else if(ev.key.toLowerCase()==='x')jumpWhere(e=>e.director_decision.committed_action.startsWith('EXIT'),1);else if(ev.key.toLowerCase()==='r')jumpWhere(e=>e.director_decision.committed_action.includes('REENTRY'),1);else if(ev.key.toLowerCase()==='b')jumpWhere(e=>e.bug_flags.length>0,1);else if(ev.key==='Home')go(0);else if(ev.key==='End')go(state.data?.events.length-1||0);}

function renderAll(){if(!state.data)return;renderStatus();renderAccount();renderNarrative();renderCharts();renderTradeSummary();renderPosition();renderTicket();renderThoughtFlow();renderMoney();renderBrain();renderDirector();renderRecommendations();renderShadowMoney();renderEquity();renderTimeline();renderStory();renderFlags();renderDebug();}

function renderStatus(){const e=event(),m=state.data.manifest,p=canonicalPaper();$('healthStrip').innerHTML=`<span>${esc(m.symbol)} <strong>${utc(e.event_time)}</strong></span><span>M1 <strong>${e.visible_m1_rows-1}</strong> · M5 <strong>${e.visible_m5_rows-1}</strong> · Event <strong>${e.event_number}</strong></span><span>Causality <strong>${esc(e.integrity.status)}</strong></span><span>Paper <strong>${esc(p?.account?.account_status||'CONFIGURE')}</strong></span><span>Orders <strong>DISABLED</strong></span>`;$('m5Title').textContent=`${m.symbol} · M5 parent`;$('m1Title').textContent=`${m.symbol} · M1 execution`;$('m5State').textContent=`${esc(e.snapshot.context?.approved_direction||'NEUTRAL')} · ${esc(e.snapshot.master_phase?.state||e.snapshot.phase?.state||'—')}`;$('m1State').textContent=`${esc(e.snapshot.m1_entry?.state||'MONITORING')} · event ${e.event_number}/${state.data.events.length-1}`;}

function metric(label,value,cls=''){return `<div class="account-metric"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong></div>`;}
function valueClass(value){return Number(value)>0?'money-positive':Number(value)<0?'money-negative':'';}
function renderAccount(){const a=canonicalPaper()?.account;if(!a){$('accountBar').innerHTML=metric('Paper account','Configure to calculate money','money-warning');return;}$('accountBar').innerHTML=[metric('Starting balance',money(a.initial_balance)),metric('Balance',money(a.current_balance),valueClass(a.current_balance-a.initial_balance)),metric('Equity',money(a.current_equity),valueClass(a.current_equity-a.initial_balance)),metric('Floating P/L',money(a.floating_pl),valueClass(a.floating_pl)),metric('Realized P/L',money(a.realized_pl),valueClass(a.realized_pl)),metric('Total costs',money(a.total_costs),'money-warning'),metric('Used margin',money(a.used_margin)),metric('Free margin',money(a.free_margin)),metric('Margin level',a.margin_level==null?'No position':pct(a.margin_level),a.margin_level!=null&&a.margin_level<150?'money-warning':''),metric('Peak equity',money(a.peak_equity)),metric('Drawdown',`${money(a.drawdown_money)} · ${pct(a.drawdown_percent)}`,a.drawdown_percent>0?'money-negative':''),metric('Return',pct(a.return_percent),valueClass(a.return_percent))].join('');}

function renderNarrative(){const e=event(),p=canonicalPaper(),decision=e.director_decision;let description=decision.narrative||'The visible prefix remains under observation.';if(p?.primary_execution_action&&p.primary_execution_action!=='NO_EXECUTION_ACTION')description+=` Paper execution: ${p.primary_execution_action.replaceAll('_',' ').toLowerCase()}.`;$('narrativeBanner').innerHTML=`<strong>${esc(decision.committed_action.replaceAll('_',' '))}</strong><span>${esc(description)}</span>`;}

function renderTradeSummary(){const s=event().snapshot,p=canonicalPaper(),a=p?.active_position||s.management?.latest_attempt||{},metrics=[['Setup',s.setup?.setup_id?.split('|').slice(-2).join(' · ')||'No active setup'],['Sequence',a.sequence_id||s.management?.sequence_id||'—'],['Attempt',a.attempt_number||s.sequence_accounting?.attempt_count||0],['Direction',a.direction||s.context?.approved_direction||'—'],['Entry',fmt(a.entry_fill_price??a.entry_price,5)],['Volume',a.volume!=null?`${fmt(a.volume,2)} lot`:'—'],['Logical stop',fmt(a.logical_stop,5)],['Emergency stop',fmt(a.emergency_stop??a.emergency_broker_stop,5)],['Current R',fmt((p?.account?.floating_pl||0)/Math.max(.000001,a.actual_logical_risk_zar||1),2)+'R'],['Peak R',fmt(a.peak_r??s.management_diagnostics?.peak_attempt_R,2)+'R']];$('tradeSummary').innerHTML=metrics.map(row=>`<div class="trade-metric"><span>${esc(row[0])}</span><strong>${esc(row[1])}</strong></div>`).join('');}

function valueBox(label,value,cls=''){return `<div class="value-box"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong></div>`;}
function renderPosition(){const p=canonicalPaper(),position=p?.active_position;if(!position){$('activePosition').innerHTML='<div class="empty-state">No paper position is open at this event. Strategy monitoring continues.</div>';return;}const a=p.account,market=p.market_price,risk=Math.max(.000001,position.actual_logical_risk_zar),r=Number(a.floating_pl)/risk;$('activePosition').innerHTML=`<div class="position-content"><div class="ticket-status"><strong>${esc(position.direction)} · ${esc(position.symbol)} · Attempt ${esc(position.attempt_number)}</strong><span class="status-pass">OPEN PAPER POSITION</span></div><div class="position-values">${[
['Entry timeframe',position.entry_timeframe],['Volume',`${fmt(position.volume,2)} lot`],['Entry request',fmt(position.entry_reference_price,5)],['Entry fill',fmt(position.entry_fill_price,5)],['Current bid',fmt(market.bid_price,5)],['Current ask',fmt(market.ask_price,5)],['Mark price',fmt(position.direction==='BULLISH'?market.bid_price:market.ask_price,5)],['Spread',`${fmt(market.spread_points,2)} points`],['Logical stop',fmt(position.logical_stop,5)],['Emergency stop',fmt(position.emergency_stop,5)],['TP1',fmt(position.target_1,5)],['Current protection',fmt(position.current_protection,5)],['Net floating',money(a.floating_pl),valueClass(a.floating_pl)],['Current R',`${fmt(r,2)}R`,valueClass(r)],['Peak R',`${fmt(position.peak_r,2)}R`,valueClass(position.peak_r)],['Logical risk',money(position.actual_logical_risk_zar)],['Emergency risk',money(position.actual_emergency_risk_zar),'money-warning'],['Margin used',money(position.margin_used_zar)],['Holding duration',`${Math.max(0,Math.round((event().event_time-position.opened_at)/60))} min`],['Spread source',market.spread_source]
].map(row=>valueBox(row[0],row[1],row[2])).join('')}</div></div>`;}

function renderTicket(){const p=canonicalPaper(),ticket=p?.last_ticket,close=p?.last_close_ticket;if(!ticket&&!close){$('paperTicket').innerHTML='<div class="empty-state">The next Director entry will produce a complete paper ticket or a visible execution rejection.</div>';return;}const row=close||ticket,fill=row.fill||{},sizing=row.sizing||{},status=row.status||'PAPER EVENT';$('paperTicket').innerHTML=`<div class="ticket-content"><div class="ticket-status"><strong>${esc(status)}</strong><span class="${status.includes('BLOCK')||status.includes('REJECT')?'status-warn':'status-pass'}">NO ORDER SENT</span></div><div class="ticket-values">${[
['Reason / signal',row.reason||row.strategy_signal],['Requested price',fmt(row.requested_exit_price??row.request?.requested_price,5)],['Bid / Ask',`${fmt(fill.bid_price,5)} / ${fmt(fill.ask_price,5)}`],['Spread',`${fmt(fill.spread_points,2)} points · ${fill.spread_source||'—'}`],['Slippage',`${fmt(fill.slippage_points,2)} points`],['Final fill',fmt(fill.final_fill_price,5)],['Ideal lots',fmt(sizing.ideal_lots,3)],['Final lots',fmt(sizing.final_lots??row.closed_volume,3)],['Logical risk',money(sizing.actual_logical_risk_zar)],['Emergency risk',money(sizing.actual_emergency_risk_zar)],['Margin',money(sizing.margin_required_zar)],['Net P/L',money(row.net_pl_zar),valueClass(row.net_pl_zar)]
].map(item=>valueBox(item[0],item[1],item[2])).join('')}</div></div>`;}

function renderThoughtFlow(){const s=event().snapshot,recs=event().recommendations,top=[...recs].sort((a,b)=>Number(b.priority)-Number(a.priority))[0];$('thoughtSee').textContent=`${s.context?.approved_direction||'NEUTRAL'} · ${s.retracement?.state||'NO RETRACEMENT'}`;$('thoughtThink').textContent=`${s.transition?.state||'WAIT'} · M1 ${s.m1_entry?.state||'WAIT'}`;$('thoughtRecommend').textContent=top?`${top.engine}: ${top.recommendation}`:'No actionable engine vote';$('thoughtCommit').textContent=event().director_decision.committed_action;}

function renderMoney(){const p=canonicalPaper(),a=p?.account||{},position=p?.active_position||{},cost=p?.cost_attribution||{},close=p?.last_close_ticket||{};const rows=[['Planned risk',money(position.planned_risk_zar)],['Actual logical risk',money(position.actual_logical_risk_zar)],['Emergency risk',money(position.actual_emergency_risk_zar)],['Spread cost',money(cost.spread_zar)],['Slippage cost',money(cost.slippage_zar)],['Commission',money(cost.commission_zar)],['Floating',money(a.floating_pl),valueClass(a.floating_pl)],['Last net result',money(close.net_pl_zar),valueClass(close.net_pl_zar)]];$('moneyStrip').innerHTML=rows.map(row=>`<div class="money-metric"><span>${esc(row[0])}</span><strong class="${row[2]||''}">${esc(row[1])}</strong></div>`).join('');}

function renderBrain(){const s=event().snapshot,p=canonicalPaper();const roots=[['HTF context',s.context?.state,s.context?.approved_direction],['Trend',s.trend?.state||s.context?.approved_direction,s.trend?.owner],['Control',s.market_control?.state||s.master_phase?.state,s.market_control?.control_side],['Impulse',s.impulse_cycle?.state||s.impulse?.state,s.impulse_cycle?.origin_bos_index],['Retracement',s.retracement?.state,s.retracement?.qualified?'Qualified':'Not qualified'],['Fib location',s.retracement?.fibonacci?.zone,fmt(s.retracement?.fibonacci?.remaining_percent,1)],['Protection',s.protection?.state,fmt(s.protection?.level,5)],['M1 quality',s.m1_entry?.state,s.m1_entry?.entry?.m1_quality_grade],['Continuation',s.transition?.state,s.transition?.recovered],['Opportunity',s.management_diagnostics?.earned_opportunity,`${fmt(s.management_diagnostics?.peak_attempt_R,2)}R peak`],['Giveback',`${fmt(s.management_diagnostics?.current_giveback_R,2)}R`,s.management_diagnostics?.deterioration],['Exhaustion',s.management_diagnostics?.exhaustion,s.management_diagnostics?.recommended_action],['Spread state',p?.market_price?.spread_state,p?.market_price?.spread_source],['Sizing',p?.last_ticket?.sizing?.status,p?.last_ticket?.sizing?.sizing_reason],['Margin',p?.account?.account_status,pct(p?.account?.margin_level)],['Conversion',p?.last_ticket?.fill?.conversion_source,p?.contract_specification?.quote_currency+' → ZAR'],['Integrity',s.integrity?.status,'Orders absent']];$('brainGrid').innerHTML=roots.map((row,index)=>`<div class="brain-card ${index>11?'debug-detail':''}"><span>${esc(row[0])}</span><strong>${esc(row[1]||'Unavailable')}</strong><small>${esc(row[2]??'')}</small></div>`).join('');$('causalBadge').textContent=`Causal ${s.integrity?.status||'—'}`;$('causalBadge').className=s.integrity?.status==='PASS'?'status-pass':'status-fail';}

function renderDirector(){const d=event().director_decision;$('directorDecision').innerHTML=`<div class="decision-action"><strong>${esc(d.committed_action)}</strong><span class="status-pass">${esc(d.safety_verdict)}</span></div><p class="decision-copy">${esc(d.narrative)}</p><dl><dt>Accepted</dt><dd>${esc(d.accepted_recommendation)}</dd><dt>Current protection</dt><dd>${esc(fmt(d.current_protection,5))}</dd><dt>Rejected alternatives</dt><dd>${esc((d.rejected_recommendations||[]).join(' · ')||'None actionable')}</dd><dt>Paper execution</dt><dd>${esc(canonicalPaper()?.primary_execution_action||'Not configured')}</dd></dl>`;}
function statusClass(value){return value==='ACCEPTED_BY_DIRECTOR'?'accepted':value==='REJECTED_BY_DIRECTOR'?'rejected':'waiting';}
function renderRecommendations(){$('recommendationRows').innerHTML=event().recommendations.map(row=>`<tr><td>${esc(row.engine)}</td><td><strong>${esc(row.recommendation)}</strong></td><td>${esc(row.priority)}</td><td>${esc(fmt(row.confidence,2))}</td><td>${esc(row.structural_owner)}<br><code>${esc(fmt(row.proposed_action,5))}</code></td><td>${esc(row.reason)}</td><td class="${statusClass(row.status)}">${esc(row.status)}</td></tr>`).join('');}
function renderShadowMoney(){const p=paper(),canonical=p?.canonical?.account;const rows=p?.shadow_accounts||[];$('shadowMoneyRows').innerHTML=canonical?`<tr><td><strong>CANONICAL</strong></td><td>${money(canonical.current_balance)}</td><td>${money(canonical.current_equity)}</td><td>${money(canonical.floating_pl)}</td><td>${pct(canonical.drawdown_percent)}</td><td>${esc(p.canonical.primary_execution_action)}</td><td>R0.00</td><td class="accepted">PASS</td></tr>`+rows.map(row=>`<tr><td>${esc(row.profile)}</td><td>${money(row.account.current_balance)}</td><td>${money(row.account.current_equity)}</td><td>${money(row.account.floating_pl)}</td><td>${pct(row.account.drawdown_percent)}</td><td>${esc(row.primary_execution_action)}</td><td class="${valueClass(row.difference_from_canonical_zar)}">${money(row.difference_from_canonical_zar)}</td><td class="accepted">${row.causal_valid?'PASS':'FAIL'}</td></tr>`).join(''):'<tr><td colspan="8">Configure the paper account to compare independent economic managers.</td></tr>';}

function equityPoints(){if(state.paper?.paper_events)return state.paper.paper_events.filter(row=>row.event_number<=state.index).map(row=>row.canonical.equity_point);const events=state.data.events.slice(0,state.index+1);return events.map(row=>row.snapshot.equity_point).filter(Boolean);}
function renderEquity(){const canvas=$('equityChart'),points=equityPoints(),dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#081421';ctx.fillRect(0,0,w,h);$('equityLegend').innerHTML='<span class="balance">Balance</span><span class="equity">Equity</span><span class="drawdown">Drawdown</span>';if(points.length<2){ctx.fillStyle='#91a6bf';ctx.fillText('Configure a paper account to display its causal equity curve.',20,30);return;}const pad={l:62,r:24,t:20,b:30},values=points.flatMap(p=>[Number(p.balance),Number(p.equity),Number(p.peak_equity)]),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||1,x=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(1,points.length-1),y=v=>pad.t+(hi-v)/span*(h-pad.t-pad.b);ctx.strokeStyle='#263b58';ctx.fillStyle='#91a6bf';ctx.font='10px Segoe UI';for(let i=0;i<5;i++){const yy=pad.t+i*(h-pad.t-pad.b)/4;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText(money(hi-i*span/4),4,yy+3);}const line=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(Number(p[key]))):ctx.moveTo(x(i),y(Number(p[key]))));ctx.stroke();};line('balance','#55a8ff');line('equity','#2ed0a5');ctx.fillStyle='rgba(242,104,128,.18)';ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(Number(p.equity))):ctx.moveTo(x(i),y(Number(p.equity))));for(let i=points.length-1;i>=0;i--)ctx.lineTo(x(i),y(Number(points[i].peak_equity)));ctx.closePath();ctx.fill();ctx.fillStyle='#91a6bf';ctx.fillText(`${points.length} causal account snapshots · click to jump`,pad.l,h-8);}
function equityJump(ev){const points=equityPoints();if(!points.length)return;const rect=$('equityChart').getBoundingClientRect(),ratio=clamp((ev.clientX-rect.left-62)/Math.max(1,rect.width-86),0,1),point=points[Math.round(ratio*(points.length-1))];if(point)go(Number(point.event_number));}

function timelineAllowed(e,filter){if(filter==='all')return true;if(filter==='significant')return e.event_priority>=55;if(filter==='trade')return e.director_decision.committed_action!=='NO_ACTION';if(filter==='management')return ['PROTECTION_MOVED','FIRST_ATTEMPT_EXITED','OPPOSING_BOS_EXIT','TARGET_STATE_CHANGED'].includes(e.event_type);return e.bug_flags.length>0;}
function renderTimeline(){const filter=$('timelineFilter').value,container=$('timeline'),rows=state.data.events.filter(row=>timelineAllowed(row,filter)&&Math.abs(row.event_number-state.index)<=70);container.innerHTML=rows.length?rows.map(row=>`<div class="timeline-event ${row.event_number===state.index?'active':''}" data-event="${row.event_number}"><time>${utc(row.event_time).slice(11,19)}</time><div><strong>${esc(row.event_type.replaceAll('_',' '))}</strong><span>${esc(row.director_decision.committed_action)} · event ${row.event_number}</span></div></div>`).join(''):'<div class="empty-state">No matching events in this window.</div>';document.querySelectorAll('.timeline-event').forEach(el=>el.onclick=()=>{pause();go(Number(el.dataset.event));});const active=container.querySelector('.timeline-event.active');if(active)container.scrollTop=Math.max(0,active.offsetTop-container.offsetTop-container.clientHeight/2);}
function renderStory(){const strategy=event().trade_story_events.slice(-12).map(row=>({...row,source:'STRATEGY'})),moneyRows=(canonicalPaper()?.money_story_events||[]).slice(-12).map(row=>({timestamp:row.timestamp,title:row.title,description:row.description,source:'MONEY'}));const rows=[...strategy,...moneyRows].sort((a,b)=>a.timestamp-b.timestamp).slice(-20);$('tradeStory').innerHTML=rows.length?rows.map(row=>`<div class="story-event"><time>${utc(row.timestamp).slice(11,19)}</time><div><strong>${esc(row.source)} · ${esc(row.title.replaceAll('_',' '))}</strong><span>${esc(row.description)}</span></div></div>`).join(''):'<div class="empty-state">Story events appear when strategy or money state changes.</div>';}
function renderFlags(){const flags=event().bug_flags;$('bugFlags').innerHTML=flags.length?flags.map(flag=>`<div class="flag-event"><strong>${esc(flag.severity)} · ${esc(flag.title)}</strong><p>${esc(flag.suggested_review_question)}</p><code>${esc(JSON.stringify(flag.evidence))}</code></div>`).join(''):'<div class="empty-state">No review flag at this event.</div>';}

function renderDebug(){const e=event();$('rawEvent').textContent=JSON.stringify({...e,paper_overlay:paper()},null,2);if(state.index===0)$('stateDiff').textContent='Replay start — no previous event.';else{const a=state.data.events[state.index-1].snapshot,b=e.snapshot,changes=[];for(const root of Object.keys(b))if(JSON.stringify(a[root])!==JSON.stringify(b[root]))changes.push({root,before:a[root],after:b[root]});$('stateDiff').textContent=JSON.stringify(changes,null,2);}const ledger=paperFinal()?.canonical?.execution_ledger||[];$('executionLedgerRows').innerHTML=ledger.filter(row=>Number(row.timestamp)<=Number(e.event_time)).slice(-100).map(row=>`<tr><td>${utc(row.timestamp).slice(11,19)}</td><td>${esc(row.action)}</td><td>${fmt(row.volume,2)}</td><td>${fmt(row.fill_price,5)}</td><td>${money(Object.values(row.costs||{}).reduce((sum,value)=>sum+Number(value||0),0))}</td><td class="${valueClass(row.net_pl)}">${money(row.net_pl)}</td><td>${money(row.balance_after)}</td></tr>`).join('');}
function renderCustomDiff(){const max=state.data.events.length-1,ai=clamp(Number($('diffA').value),0,max),bi=clamp(Number($('diffB').value),0,max),a=state.data.events[ai].snapshot,b=state.data.events[bi].snapshot,changes=[];const walk=(x,y,path)=>{if(x&&y&&typeof x==='object'&&typeof y==='object'&&!Array.isArray(x)&&!Array.isArray(y)){for(const key of new Set([...Object.keys(x),...Object.keys(y)]))walk(x[key],y[key],path?`${path}.${key}`:key);}else if(JSON.stringify(x)!==JSON.stringify(y))changes.push({field:path,before:x,after:y});};walk(a,b,'');$('stateDiff').textContent=JSON.stringify({event_A:ai,event_B:bi,changes},null,2);}

function fullVisibleRows(tf){const e=event(),all=state.data.candles[tf],limit=tf==='M1'?e.visible_m1_rows-1:e.visible_m5_rows-1;return all.filter(row=>row.index<=limit);}
function visibleRows(tf){const rows=fullVisibleRows(tf),view=state.views[tf],end=Math.max(0,rows.length-view.offset),start=Math.max(0,end-view.window);return rows.slice(start,end);}
function chartWheel(ev){ev.preventDefault();const tf=ev.currentTarget.id==='m5Chart'?'M5':'M1',view=state.views[tf];if(ev.shiftKey){view.priceZoom=clamp(view.priceZoom*Math.exp(-ev.deltaY*.0015),.55,6);}else{const total=fullVisibleRows(tf).length;view.window=Math.round(clamp(view.window*Math.exp(ev.deltaY*.0012),20,Math.max(20,total)));}renderCharts();}
function chartDragStart(ev){const tf=ev.currentTarget.id==='m5Chart'?'M5':'M1';state.drag={tf,startX:ev.clientX,startOffset:state.views[tf].offset};}
function chartMouse(ev){if(!state.data)return;const canvas=ev.currentTarget,tf=canvas.id==='m5Chart'?'M5':'M1',rows=visibleRows(tf),rect=canvas.getBoundingClientRect();if(state.drag&&state.drag.tf===tf&&ev.buttons===1){const pixelsPerCandle=Math.max(2,(rect.width-120)/Math.max(1,rows.length)),delta=Math.round((ev.clientX-state.drag.startX)/pixelsPerCandle);state.views[tf].offset=clamp(state.drag.startOffset-delta,0,Math.max(0,fullVisibleRows(tf).length-state.views[tf].window));renderCharts();return;}if(!rows.length)return;const index=clamp(Math.round((ev.clientX-rect.left-55)/Math.max(1,rect.width-120)*(rows.length-1)),0,rows.length-1),row=rows[index];state.cursorTime=row.time;const p=canonicalPaper()?.market_price||{};$(tf==='M5'?'m5Hover':'m1Hover').textContent=`${utc(row.time)} · O ${fmt(row.open,5)} H ${fmt(row.high,5)} L ${fmt(row.low,5)} C ${fmt(row.close,5)} · execution bid ${fmt(p.bid_price,5)} ask ${fmt(p.ask_price,5)} spread ${fmt(p.spread_points,2)} pts · index ${row.index}`;renderCharts();}
function renderCharts(){if(!state.data)return;drawChart($('m5Chart'),'M5');drawChart($('m1Chart'),'M1');}
function drawChart(canvas,tf){const rows=visibleRows(tf),dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#071321';ctx.fillRect(0,0,w,h);if(!rows.length)return;const pad={l:55,r:80,t:22,b:30},s=event().snapshot,paperState=canonicalPaper(),prices=[];let lo=Math.min(...rows.map(row=>row.low)),hi=Math.max(...rows.map(row=>row.high));if(state.layers.Fibonacci)Object.values(s.retracement?.fibonacci?.levels||{}).forEach(value=>prices.push(Number(value)));const attempt=paperState?.active_position||s.management?.latest_attempt||{};['logical_stop','emergency_stop','emergency_broker_stop','target_1','position_1_target','current_protection','entry_fill_price','entry_price'].forEach(key=>{const value=attempt[key];if(value!=null)prices.push(Number(value));});prices.filter(Number.isFinite).forEach(value=>{lo=Math.min(lo,value);hi=Math.max(hi,value);});let center=(lo+hi)/2,span=(hi-lo)*1.14||1;span/=state.views[tf].priceZoom;lo=center-span/2;hi=center+span/2;const x=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(1,rows.length-1),y=price=>pad.t+(hi-price)/(hi-lo)*(h-pad.t-pad.b);
  ctx.strokeStyle='#203650';ctx.lineWidth=.6;ctx.font='10px Segoe UI';ctx.fillStyle='#8298b2';for(let i=0;i<=5;i++){const yy=pad.t+i*(h-pad.t-pad.b)/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillText(fmt(hi-i*(hi-lo)/5,5),w-pad.r+7,yy+3);}for(let i=0;i<rows.length;i+=Math.max(1,Math.floor(rows.length/7))){const xx=x(i);ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillText(new Date(rows[i].time*1000).toISOString().slice(11,16),Math.max(0,xx-14),h-8);}
  if(state.layers.Retracement&&s.retracement?.qualified){const start=s.retracement.initial_pullback_start,end=s.retracement.current_pullback_end,ai=rows.findIndex(row=>row.index>=start),bi=rows.findIndex(row=>row.index>=end);if(ai>=0){ctx.fillStyle='rgba(178,140,255,.08)';ctx.fillRect(x(ai),pad.t,x(bi<0?rows.length-1:bi)-x(ai),h-pad.t-pad.b);}}
  if(state.layers.Fibonacci)for(const [label,price] of Object.entries(s.retracement?.fibonacci?.levels||{}))line(Number(price),'rgba(52,202,214,.55)',.7,[3,4],`Fib ${label}%`);
  const bodyW=Math.max(2,Math.min(9,(w-pad.l-pad.r)/rows.length*.62));rows.forEach((row,i)=>{const xx=x(i),up=row.close>=row.open,color=up?'#2ed0a5':'#f26880';ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,y(row.high));ctx.lineTo(xx,y(row.low));ctx.stroke();ctx.fillStyle=color;ctx.fillRect(xx-bodyW/2,y(Math.max(row.open,row.close)),bodyW,Math.max(1,Math.abs(y(row.open)-y(row.close))));});
  const confirmed_swings=(s.structure?.confirmed_swings||[]).filter(point=>rows.some(row=>row.index===point.index));if(state.layers['Meaningful swings']||state.layers['HH/HL/LH/LL']){ctx.font='10px Segoe UI';for(const point of confirmed_swings){const i=rows.findIndex(row=>row.index===point.index),yy=y(point.level)+(point.side==='HIGH'?-8:14);ctx.fillStyle=point.side==='HIGH'?'#ffd477':'#8fcbff';ctx.textAlign='center';ctx.fillText(state.layers['HH/HL/LH/LL']?(point.classification||point.side):(point.side==='HIGH'?'▲':'▼'),x(i),yy);}}
  const entryPrice=attempt.entry_fill_price??attempt.entry_price??s.entry?.price;if(state.layers['Entry triggers']&&entryPrice!=null)line(Number(entryPrice),'#55a8ff',1.5,[],`PAPER ENTRY ${fmt(entryPrice,5)}`);if(state.layers['Initial logical stop']&&attempt.logical_stop!=null)line(Number(attempt.logical_stop),'#f4bd55',1,[7,4],`LOGICAL ${fmt(attempt.logical_stop,5)}`);const emergency=attempt.emergency_stop??attempt.emergency_broker_stop;if(state.layers['Emergency stop']&&emergency!=null)line(Number(emergency),'#f26880',1,[2,4],`EMERGENCY ${fmt(emergency,5)}`);const target=attempt.target_1??attempt.position_1_target;if(state.layers.Targets&&target!=null)line(Number(target),'#2ed0a5',1,[7,4],`TP1 ${fmt(target,5)}`);if(state.layers['Proven trails']&&attempt.current_protection!=null)line(Number(attempt.current_protection),'#b28cff',1.5,[],`PROTECTION ${fmt(attempt.current_protection,5)}`);if(state.layers['Dominant protection']&&s.protection?.level!=null)line(Number(s.protection.level),'rgba(46,208,165,.7)',1,[],`DOMINANT ${fmt(s.protection.level,5)}`);
  const market=paperState?.market_price;if(state.layers['Bid / ask / spread']&&market&&(paperState.active_position||state.mode==='debug')){const bid=Number(market.bid_price),ask=Number(market.ask_price);if(bid>=lo&&bid<=hi&&ask>=lo&&ask<=hi){ctx.fillStyle='rgba(244,189,85,.08)';ctx.fillRect(pad.l,Math.min(y(bid),y(ask)),w-pad.l-pad.r,Math.abs(y(bid)-y(ask)));line(bid,'rgba(85,168,255,.75)',.8,[4,3],`BID ${fmt(bid,5)}`);line(ask,'rgba(244,189,85,.75)',.8,[4,3],`ASK ${fmt(ask,5)}`);}}
  const current=rows.length-1;ctx.fillStyle='rgba(85,168,255,.10)';ctx.fillRect(x(current)-bodyW,pad.t,bodyW*2,h-pad.t-pad.b);if(state.cursorTime!=null){let i=rows.reduce((best,row,j)=>Math.abs(row.time-state.cursorTime)<Math.abs(rows[best].time-state.cursorTime)?j:best,0);ctx.strokeStyle='rgba(220,232,247,.55)';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x(i),pad.t);ctx.lineTo(x(i),h-pad.b);ctx.stroke();ctx.setLineDash([]);}ctx.fillStyle='#8298b2';ctx.textAlign='left';ctx.fillText(`${tf} · ${rows.length}/${fullVisibleRows(tf).length} revealed candles · future region empty`,pad.l,13);
  function line(price,color,width,dash,label){if(!Number.isFinite(price)||price<lo||price>hi)return;const yy=y(price);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.textAlign='left';ctx.fillText(label,pad.l+5,yy-3);}
}

function downloadEvent(){const payload={strategy_event:event(),paper_execution:paper(),account_configuration:state.accountConfig,execution_configuration:state.executionConfig},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download=`${state.data.manifest.replay_session_id}_event_${state.index}_paper.json`;anchor.click();URL.revokeObjectURL(anchor.href);}
async function saveReview(){const payload={session_id:state.data.manifest.replay_session_id,event_number:state.index,event_id:event().replay_event_id,entry:$('reviewEntry').value,stop:$('reviewStop').value,management:$('reviewManagement').value,reentry:$('reviewReentry').value,bug_flag_status:$('reviewFlag').value,notes:$('reviewNotes').value,canonical_state_mutated:false,paper_state_mutated:false};const output=await jsonFetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('reviewStatus').textContent=output.saved?'Saved outside canonical and paper state':'Save failed';}

async function loadLibrary(){const response=await jsonFetch('/api/data-library');state.library=response.symbols||[];$('libraryRows').innerHTML=state.library.map(row=>`<tr><td><strong>${esc(row.symbol)}</strong></td><td>${utc(row.timeframes.M1.first_timestamp).slice(0,16)} → ${utc(row.timeframes.M1.last_timestamp).slice(0,16)}</td><td>${utc(row.timeframes.M5.first_timestamp).slice(0,16)} → ${utc(row.timeframes.M5.last_timestamp).slice(0,16)}</td><td>${esc(row.timeframes.M1.rows)} / ${esc(row.timeframes.M5.rows)}</td><td>${esc(row.timeframes.M1.spread_availability)}</td><td>${esc(row.contract_spec_source)}</td><td class="accepted">${esc(row.replay_readiness)}</td></tr>`).join('');$('buildSymbol').innerHTML=state.library.map(row=>`<option value="${esc(row.symbol)}">${esc(row.symbol)}</option>`).join('');$('buildSymbol').onchange=syncBuildRange;syncBuildRange();}
function syncBuildRange(){const row=state.library.find(item=>item.symbol===$('buildSymbol').value);if(!row)return;const start=new Date((Number(row.timeframes.M1.first_timestamp)+3600)*1000).toISOString().slice(0,16),end=new Date(Math.min(Number(row.timeframes.M1.last_timestamp),Number(row.timeframes.M5.last_timestamp))*1000).toISOString().slice(0,16);$('buildStart').value=start;$('buildEnd').value=end;}
async function buildReplay(ev){ev.preventDefault();const config=currentConfigurations(),request={symbol:$('buildSymbol').value,start:new Date($('buildStart').value+'Z').toISOString(),end:new Date($('buildEnd').value+'Z').toISOString(),context_preload:Number($('buildContext').value),max_events:Number($('buildMaxEvents').value),account_configuration:config.account,execution_configuration:config.execution,shadow_managers:['CANONICAL','PURE_STRUCTURE_RUNNER','TP1_PARTIAL_PLUS_RUNNER','EARNED_OPPORTUNITY_MANAGER'],bug_rules:['FINANCIAL','MANAGEMENT','CAUSALITY']};$('buildProgress').textContent='Submitting safe configured-library build…';try{const job=await jsonFetch('/api/replay/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});pollBuild(job.job_id);}catch(error){$('buildProgress').textContent=`Build rejected: ${error.message}`;}}
async function pollBuild(jobId){try{const job=await jsonFetch(`/api/replay/build/${encodeURIComponent(jobId)}/status`);$('buildProgress').innerHTML=`<strong>${esc(job.status)} · ${esc(job.stage)}</strong><br>${fmt(job.progress_percent,1)}% · ${esc(job.processed_events)}/${esc(job.estimated_events)} events${job.errors?.length?`<br>${esc(job.errors.join(' · '))}`:''}`;if(job.status==='COMPLETE'){state.sessions=await jsonFetch('/api/sessions');populateSessions();$('sessionSelect').value=job.session_id;await loadSession(job.session_id,true);$('dataLibraryPanel').classList.add('hidden');return;}if(job.status!=='FAILED')setTimeout(()=>pollBuild(jobId),1000);}catch(error){$('buildProgress').textContent=`Status error: ${error.message}`;}}

boot().catch(error=>{$('narrativeBanner').innerHTML=`<strong>Simulator error</strong><span>${esc(error.message)}</span>`;console.error(error);});
